{"name": "Ошибка при создании курьера с занятым логином", "status": "passed", "description": "Проверяем, что нельзя зарегистрировать курьера с уже существующим логином. Код ответа: 409.", "start": 1737560022896, "stop": 1737560053281, "uuid": "4f580b89-b0aa-4a50-bb0e-eedd9c41f828", "historyId": "6f67603245d03577c0bb7ad6998f5f65", "testCaseId": "6f67603245d03577c0bb7ad6998f5f65", "fullName": "tests.test_courier_create.TestCourierCreate#test_create_courier_account_login_taken_conflict", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_create"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "DESKTOP-T8QAB49"}, {"name": "thread", "value": "24840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_create"}]}